### ISSUE TITLE
WARNING: Removing column '743' composed only by gaps

### ISSUE THREAD

**Issue by MaxBai0123** [scapella/trimal#71]
![image](https://user-images.githubusercontent.com/118806130/226150831-9cefaeb4-7c72-4d1f-a9e9-9e82bf1653be.png)
Hi~,I used trimal to trim my mafft result, but it tell me warning, I not't know why？

**Comment by NickSomsen** [comment]
It probably means that the automated filtering resulted in columns `743` and `1697` to be completely composed out of gaps, i.e. every single sequence has a gap in the alignment at those 2 positions. These gap columns can then be removed since they do not give any information anymore. (this is the result of the `-noallgaps` option which seems to be used automatically when using `automated1`).

The same can happen with entire sequences, it will then give a warning like the following:
```
WARNING: Removing sequence '>my_seq' composed only by gaps
```
This can however be prevented by using the `-keepseqs` option.
