### ISSUE TITLE
How to only trim terminal of the alignment with a threshold value of gap

### ISSUE THREAD

**Issue by permia** [scapella/trimal#98]
I want to trim gappy terminal of an alignments until the gap > 0.1. I don't want to trim the internal site below the threshold. Firtly, I think  `-terminalonly` may work. But it doesn't.

`-terminalonly`
Only columns out of internal boundaries (first and last column without gaps) are candidated to be trimmed depending on the applied method.

I think it may only trim the boudary of the alignments. But I found it also trims internal column if some sequences are short.

e.g. I have a file named `1.afa`

```
>1
-GGNVPFSDI
>2
--AAT-ADQV
>3
--------RA
>4
--DR----PV
>5
--GA----PL
>6
--GQ----PV
>7
--GK----PA
>8
--GK----PA
>9
--GK----PA
>10
--GK----PA
```
When I trimed it with:
`trimal -terminalonly -gt 0.01 -in 1.fasta`
```
>1
-GNVPFSDI
>2
-AAT-ADQV
>3
-------RA
>4
-DR----PV
>5
-GA----PL
>6
-GQ----PV
>7
-GK----PA
>8
-GK----PA
>9
-GK----PA
>10
GGK----PA
```
The first column with all gaps was delete, which was I want.  But when I try to trim the second column.

`trimal -terminalonly -gt 0.1 -in 1.fasta`

```
>1
GNVFSDI
>2
AATADQV
>3
-----RA
>4
DR---PV
>5
GA---PL
>6
GQ---PV
>7
GK---PA
>8
GK---PA
>9
GK---PA
>10
GK---PA
```

Not only the firt two column, but the sixth column was also delete owing to this site was terminal of sequence 3.

**Comment by nicodr97** [comment]
Hi @permia,

As you experienced, `-terminalonly` will consider removing only columns out of boundaries (the first and last column without gaps). In your example, those boundary columns are column 9 and 10, which in this case are also the only ones with no gap. That's why `trimal -terminalonly -gt 0.1 -in 1.fasta` removes also the 6th column. 

In the version on the [main branch](https://github.com/inab/trimal) there is a new parameter called `--set_boundaries` which may be useful for what you want. For instance, you could run this command to keep those central columns: `trimal -terminalonly -gt 0.1 -in 1.fasta --set_boundaries { 2,9 }`
